# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-11 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockanswer',
            name='ans_header',
            field=models.CharField(default='', max_length=500),
        ),
    ]
